name: test-chromedriver-mysql

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11"]

    env:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root:myPassword@127.0.0.1:3306/rails_development_db
      RUBYOPT: -EUTF-8
      SELENIUM_CHROME_HEADLESS: true
      chromedriver_version: '88.0.4324.96'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: rails_development_db
          MYSQL_ROOT_PASSWORD: myPassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: select_db
        run: |
          mysql -h"127.0.0.1" -uroot -p'myPassword' -e "show databases"
          echo " "
          mysql -h"127.0.0.1" -uroot -p'myPassword' -e "show tables" -D rails_development_db
          echo " "
          mysql -h"127.0.0.1" -uroot -p'myPassword'  -D rails_development_db -e "CREATE TABLE IF NOT EXISTS table_user_b( id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL DEFAULT '',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP )ENGINE=INNODB;"
          echo " "
          mysql -h"127.0.0.1" -uroot -p'myPassword' -e "show tables" -D rails_development_db
          echo " "
          mysql -h"127.0.0.1" -uroot -p'myPassword' -D rails_development_db -e "insert into table_user_b(title,created_at) values(now(),now() )"
          echo " "
          mysql -h"127.0.0.1" -uroot -p'myPassword' -D rails_development_db -e "select * from table_user_b"
          echo " "
      - name: list
        run: |
          ls -la ./
          echo ""
          chmod u+x ./test_chromedriver.sh
          echo ""
          ls -la ./test_chromedriver.sh
          echo ""
          cat ./monthly.txt
          echo ""
      - name: exec_sh
        run: |
          chmod +x ./test_chromedriver.sh
          echo ""
          ./test_chromedriver.sh  $chromedriver_version  "linux64"
#          cat ./test_chromedriver.sh
#          echo ""
#          ./test_chromedriver.sh  $chromedriver-version  "linux64"
#          bash ./test_chromedriver.sh
        shell: bash
      # - name: Run Python File
      #   run: |
      #     python openUrl.py
      - name: list
        run: |
          ls -la ./
          echo ""
          # ls -la ./image_path
          # echo ""
      - name: log
        run: |
          git log
          command -v sudo dpkg-query -l "*google-chrome*"

      - name: push
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git status
          git add ./image_path
          git commit -m "$(date '+%Y.%m.%d %H:%M:%S') Monthly update"
          git push origin

